// import connectPgSimple from 'connect-pg-simple';
// import 'dotenv/config';
// import express, { Express } from 'express';
// import session from 'express-session';
// import './config.js';
// import { characterController } from './controllers/characterController.js';
// import { itemController } from './controllers/itemController.js';
// import { noteController } from './controllers/noteController.js';
// import { sharingController } from './controllers/sharingController.js';
// import { userController } from './controllers/userController.js';
// import { sessionMiddleware } from './sessionConfig.js';

// const app: Express = express();
// const { COOKIE_SECRET } = process.env;
// const PostgresStore = connectPgSimple(session);

// app.use(sessionMiddleware); // Setup session management middleware
// app.use(express.json()); // Setup JSON body parsing middleware
// app.use(express.urlencoded({ extended: false })); // Setup urlencoded (HTML Forms) body parsing middleware

// // Setup static resource file middleware
// // This allows the client to access any file inside the `public` directory
// // Only put file that you actually want to be publicly accessibly in the `public` folder
// app.use(express.static('public', { extensions: ['html'] }));
// app.use(express.json());
// app.use(
//   session({
//     store: new PostgresStore({ createTableIfMissing: true }),
//     secret: COOKIE_SECRET,
//     cookie: { maxAge: 8 * 60 * 60 * 1000 },
//     name: 'session',
//     resave: false,
//     saveUninitialized: false,
//   }),
// );

// // -- Routes --------------------------------------------------
// // Register your routes below this line

// // #### USER ROUTES #### //
// app.post('/users', userController.registerUser);
// app.post('/login', userController.logIn);
// app.delete('/sessions', userController.logOut);
// app.get('/users/me', userController.getUserProfile);
// app.delete('/users/me', userController.deleteUser);
// app.put('/users/me', userController.changeDisplayName);
// // #### CHARACTER CREATOR ROUTES #### //
// app.post('/characters', characterController.createCharacter);
// app.get('/characters/:id', characterController.getCharacter);
// app.get('/characters/', characterController.getManyCharacters);
// app.delete('/characters/:id', characterController.deleteCharacter);
// app.patch('/characters/:id', characterController.updateCharacter);
// // #### INVENTORY ROUTES #### //
// app.post('/characters/:id/items', itemController.addItem);
// app.get('/characters/:id/items', itemController.getInventory);
// app.put('/items/:id', itemController.updateItem);
// app.delete('/characters/:id/items/:id', itemController.deleteItem);
// // #### NOTE ROUTES #### //
// app.post('/characters/:id/notes', noteController.addNote);
// app.get('/characters/:id/notes', noteController.getNotes);
// app.put('/notes/:id', noteController.updateNote);
// app.delete('/characters/:id/notes/:id', noteController.deleteNote);
// // #### SHARING ROUTES #### //
// app.post('/characters/:id/share', sharingController.shareCharacterWithUser);
// app.delete('/characters/:id/share', sharingController.unshareCharacter);

// app.listen(process.env.PORT, () => {
//   console.log(`Server listening on http://localhost:${process.env.PORT}`);
// });

import express, { Express } from 'express';
import './config.js'; // do not remove this line
import { characterController } from './controllers/characterController.js';
import { itemController } from './controllers/itemController.js';
import { noteController } from './controllers/noteController.js';
import { sharingController } from './controllers/sharingController.js';
import { userController } from './controllers/userController.js';
import { sessionMiddleware } from './sessionConfig.js';

const app: Express = express();

app.use(sessionMiddleware); // Setup session management middleware
app.use(express.json()); // Setup JSON body parsing middleware
app.use(express.urlencoded({ extended: false })); // Setup urlencoded (HTML Forms) body parsing middleware

// Setup static resource file middleware
// This allows the client to access any file inside the `public` directory
// Only put file that you actually want to be publicly accessibly in the `public` folder
app.use(express.static('public', { extensions: ['html'] }));

// Serve the built Svelte frontend (generated by `npm run build:client`)
app.use(express.static('frontend/build'));

// -- Routes --------------------------------------------------
// Register your routes below this line (prefix with `/api`)

// Returns the signed-in user (or 401). The frontend's auth store
// calls this on every page load.
app.get('/api/me', (req, res) => {
  if (!req.session.isLoggedIn || !req.session.authenticatedUser) {
    res.sendStatus(401);
    return;
  }

  const { userId, email, displayName } = req.session.authenticatedUser;
  res.json({ id: userId, email, displayName });
});

// #### USER ROUTES #### //
app.post('/api/users', userController.registerUser);
app.post('/api/login', userController.logIn);
app.delete('/api/sessions', userController.logOut);
app.get('/api/users/me', userController.getUserProfile);
app.delete('/api/users/me', userController.deleteUser);
app.put('/api/users/me', userController.changeDisplayName);
// #### CHARACTER CREATOR ROUTES #### //
app.post('/api/characters', characterController.createCharacter);
app.get('/api/characters/:id', characterController.getCharacter);
app.get('/api/characters/', characterController.getManyCharacters);
app.delete('/api/characters/:id', characterController.deleteCharacter);
app.patch('/api/characters/:id', characterController.updateCharacter);
// #### INVENTORY ROUTES #### //
app.post('/api/characters/:id/items', itemController.addItem);
app.get('/api/characters/:id/items', itemController.getInventory);
app.put('/api/items/:id', itemController.updateItem);
app.delete('/api/characters/:id/items/:id', itemController.deleteItem);
// #### NOTE ROUTES #### //
app.post('/api/characters/:id/notes', noteController.addNote);
app.get('/api/characters/:id/notes', noteController.getNotes);
app.put('/api/notes/:id', noteController.updateNote);
app.delete('/api/characters/:id/notes/:id', noteController.deleteNote);
// #### SHARING ROUTES #### //
app.post('/api/characters/:id/share', sharingController.shareCharacterWithUser);
app.delete('/api/characters/:id/share', sharingController.unshareCharacter);

// -- SPA fallback --------------------------------------------
// Keep these LAST, after every `/api/*` route.
// Any unmatched `/api/*` request gets a JSON-safe 404.
app.use('/api', (req, res) => {
  res.sendStatus(404);
});

// Any other unmatched request falls back to the Svelte app so
// client-side routing works on refresh.
app.use((req, res) => {
  res.sendFile('index.html', { root: 'frontend/build' });
});

app.listen(process.env.PORT, () => {
  console.log(`Server listening on http://localhost:${process.env.PORT}`);
});
